// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvX6_eafhVxDhuXBTHTUE5eH4CnCtyVD8',
    appId: '1:1015422183731:web:700f9cecc1e5c739503646',
    messagingSenderId: '1015422183731',
    projectId: 'kalleritemple-78c37',
    authDomain: 'kalleritemple-78c37.firebaseapp.com',
    databaseURL: 'https://kalleritemple-78c37-default-rtdb.firebaseio.com',
    storageBucket: 'kalleritemple-78c37.firebasestorage.app',
    measurementId: 'G-35D1HNMDHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCApp8WtUfRPkRKEOf9-h_xr7mObk1ypO0',
    appId: '1:1015422183731:android:27d986571e568590503646',
    messagingSenderId: '1015422183731',
    projectId: 'kalleritemple-78c37',
    databaseURL: 'https://kalleritemple-78c37-default-rtdb.firebaseio.com',
    storageBucket: 'kalleritemple-78c37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKLh-XbKarx4K-nMH3VXgDvk8ajaxW1oM',
    appId: '1:1015422183731:ios:81ede9f059f8f8cf503646',
    messagingSenderId: '1015422183731',
    projectId: 'kalleritemple-78c37',
    databaseURL: 'https://kalleritemple-78c37-default-rtdb.firebaseio.com',
    storageBucket: 'kalleritemple-78c37.firebasestorage.app',
    iosBundleId: 'com.appletlogic.kalleriEmpleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKLh-XbKarx4K-nMH3VXgDvk8ajaxW1oM',
    appId: '1:1015422183731:ios:81ede9f059f8f8cf503646',
    messagingSenderId: '1015422183731',
    projectId: 'kalleritemple-78c37',
    databaseURL: 'https://kalleritemple-78c37-default-rtdb.firebaseio.com',
    storageBucket: 'kalleritemple-78c37.firebasestorage.app',
    iosBundleId: 'com.appletlogic.kalleriEmpleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvX6_eafhVxDhuXBTHTUE5eH4CnCtyVD8',
    appId: '1:1015422183731:web:280c2dd8a3fbd399503646',
    messagingSenderId: '1015422183731',
    projectId: 'kalleritemple-78c37',
    authDomain: 'kalleritemple-78c37.firebaseapp.com',
    databaseURL: 'https://kalleritemple-78c37-default-rtdb.firebaseio.com',
    storageBucket: 'kalleritemple-78c37.firebasestorage.app',
    measurementId: 'G-ZE3KXJPRSG',
  );
}
